=== motor101/gitProject/hotelsCatalog.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT catalog (reg:regions, hotels)>
<!ELEMENT reg:regions (reg:region+)>
<!ELEMENT reg:region (reg:name)>
<!ELEMENT reg:name (#PCDATA)>
<!ELEMENT hotels (hotel+)>
<!ELEMENT hotel (name, description, starsCategory, telephone, email, image)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT starsCategory (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT image EMPTY>

<!ATTLIST reg:regions xmlns:reg CDATA #REQUIRED>
<!ATTLIST reg:region id ID #REQUIRED>
<!ATTLIST hotel id ID #REQUIRED>
<!ATTLIST hotel regionId IDREF #REQUIRED>
<!ATTLIST image href ENTITY #REQUIRED>
<!NOTATION jpg PUBLIC "jpg viewer">

=== motor101/gitProject/hotelsCatalog.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="hotelsCatalog.xsl"?>

<!DOCTYPE catalog SYSTEM "hotelsCatalog.dtd" [
    <!ENTITY h1 SYSTEM "images/.jpg" NDATA jpg>
    <!ENTITY h2 SYSTEM "images/.jpg" NDATA jpg>
    <!ENTITY h3 SYSTEM "images/.jpg" NDATA jpg>
    <!ENTITY h4 SYSTEM "images/.jpg" NDATA jpg>
    <!ENTITY h5 SYSTEM "images/.jpg" NDATA jpg>
    <!ENTITY h6 SYSTEM "images/.jpg" NDATA jpg>
    <!ENTITY h7 SYSTEM "images/.jpg" NDATA jpg>
    <!ENTITY h8 SYSTEM "images/.jpg" NDATA jpg>
]>

<catalog>
    <reg:regions xmlns:reg="http://hotel.catalog.com/regions">
        <reg:region id="region_1">
            <reg:name></reg:name>
        </reg:region>
    </reg:regions>
    <hotels>
        <hotel id="hotel_1" regionId="region_1">
            <name></name>
            <description></description>
            <starsCategory></starsCategory>
            <telephone></telephone>
            <email></email>
            <image href="h1"/>
        </hotel>
    </hotels>
</catalog>
